/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { readFile, rm, mkdir, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const magentaRootDir = resolve(__dirname, "fixtures/magento-root");
const fixtureDir = resolve(magentaRootDir, "tailwind");
const generatedDir = resolve(fixtureDir, "generated");
const generatedFile = resolve(generatedDir, "hyva-source.css");
const binPath = resolve(__dirname, "../bin/generate-sources.js");

const runGenerateSources = () =>
    new Promise((resolve, reject) => {
        const child = spawn(process.execPath, [binPath], { cwd: fixtureDir });
        let stderr = "";
        child.stderr.on("data", (data) => (stderr += data));
        child.on("close", (code) => {
            if (code === 0) resolve();
            else reject(new Error(`Process exited with code ${code}\n${stderr}`));
        });
    });

const keep = process.argv.includes("--keep");

before(async () => {
    await rm(magentaRootDir, { recursive: true, force: true });
    await mkdir(resolve(magentaRootDir, "app/etc"), { recursive: true });
    await mkdir(resolve(magentaRootDir, "app/code/Vendor/HyvaModule"), { recursive: true });
    await mkdir(resolve(magentaRootDir, "vendor"), { recursive: true });
    await mkdir(fixtureDir, { recursive: true });
    await writeFile(
        resolve(magentaRootDir, "app/etc/hyva-themes.json"),
        JSON.stringify({ extensions: [{ src: "app/code/Vendor/HyvaModule" }] }, null, 4)
    );
    await writeFile(resolve(fixtureDir, "hyva.config.json"), JSON.stringify({}, null, 4));
    await runGenerateSources();
});

after(async () => {
    if (!keep) await rm(magentaRootDir, { recursive: true, force: true });
});

test("generates hyva-source.css", async () => {
    const css = await readFile(generatedFile, "utf8");
    assert.ok(css.length > 0, "file should not be empty");
});

test("includes auto-generated comment", async () => {
    const css = await readFile(generatedFile, "utf8");
    assert.ok(
        css.includes("This file is automatically generated."),
        "should contain auto-generated comment"
    );
});

test("generates @source statement for extension module", async () => {
    const css = await readFile(generatedFile, "utf8");
    assert.ok(
        css.includes('@source "../../app/code/Vendor/HyvaModule"'),
        "should contain @source glob for module"
    );
});
