/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { readFile, rm, mkdir, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixtureDir = resolve(__dirname, "fixtures/tailwind");
const generatedDir = resolve(fixtureDir, "generated");
const generatedFile = resolve(generatedDir, "hyva-tokens.css");
const binPath = resolve(__dirname, "../bin/generate-tokens.js");

const runGenerateTokens = () =>
    new Promise((resolve, reject) => {
        const child = spawn(process.execPath, [binPath], { cwd: fixtureDir });
        let stderr = "";
        child.stderr.on("data", (data) => (stderr += data));
        child.on("close", (code) => {
            if (code === 0) resolve();
            else reject(new Error(`Process exited with code ${code}\n${stderr}`));
        });
    });

before(async () => {
    await rm(fixtureDir, { recursive: true, force: true });
    await mkdir(fixtureDir, { recursive: true });
    await writeFile(resolve(fixtureDir, "hyva.config.json"), JSON.stringify({
        tokens: {
            cssSelector: "@theme",
            values: {
                color: {
                    primary: "#ff0000",
                    secondary: "#00ff00",
                },
                fontSize: {
                    sm: "0.875rem",
                    base: "1rem",
                    lg: "1.125rem",
                },
                fontFamilies: {
                    standard: { $value: "Arial, sans-serif" },
                    heading: { $value: "{fontFamilies.standard}" },
                },
            },
        },
    }, null, 4));
    await runGenerateTokens();
});

after(async () => {
    await rm(fixtureDir, { recursive: true, force: true });
});

test("generates hyva-tokens.css", async () => {
    const css = await readFile(generatedFile, "utf8");
    assert.ok(css.length > 0, "file should not be empty");
    assert.ok(
        css.includes("This file is automatically generated"),
        "should contain auto-generated comment"
    );
});

test("wraps tokens in @theme selector", async () => {
    const css = await readFile(generatedFile, "utf8");
    assert.ok(css.includes("@theme {"), "should contain @theme selector");
});

test("generates color tokens", async () => {
    const css = await readFile(generatedFile, "utf8");
    assert.ok(css.includes("--color-primary: #ff0000"), "should contain --color-primary");
    assert.ok(css.includes("--color-secondary: #00ff00"), "should contain --color-secondary");
});

test("generates font-size tokens", async () => {
    const css = await readFile(generatedFile, "utf8");
    assert.ok(css.includes("--font-size-sm: 0.875rem"), "should contain --font-size-sm");
    assert.ok(css.includes("--font-size-base: 1rem"), "should contain --font-size-base");
    assert.ok(css.includes("--font-size-lg: 1.125rem"), "should contain --font-size-lg");
});

test("converts token references to CSS variables", async () => {
    const css = await readFile(generatedFile, "utf8");
    assert.ok(
        css.includes("var(--fontFamilies-standard)"),
        "should convert {fontFamilies.standard} to var(--fontFamilies-standard)"
    );
});
