/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

import { formatFromFile } from "./config.js";

/**
 * Quote a font family name for use in CSS.
 *
 * @param {string} family
 * @returns {string} quoted family name
 */
export function quoteFamily(family) {
    return /^[a-zA-Z][a-zA-Z0-9-]*$/.test(family) ? family : `"${family}"`;
}

/**
 * Render a single @font-face rule.
 *
 * @param {Object} face - Resolved face.
 * @param {string} face.family
 * @param {string} face.style
 * @param {string} face.weight
 * @param {string} [face.stretch]
 * @param {string} [face.display]
 * @param {string} [face.unicodeRange]
 * @param {string[]} face.files - Font file paths, relative to the CSS output.
 * @returns {string} CSS
 */
export function renderFontFace(face) {
    const src = face.files
        .map((file) => `url("${file}") format("${formatFromFile(file)}")`)
        .join(",\n         ");

    const declarations = [
        `font-family: ${quoteFamily(face.family)}`,
        `font-style: ${face.style}`,
        `font-weight: ${face.weight}`,
        face.stretch && `font-stretch: ${face.stretch}`,
        face.display && `font-display: ${face.display}`,
        `src: ${src}`,
        face.unicodeRange && `unicode-range: ${face.unicodeRange}`,
    ].filter(Boolean);

    return `@font-face {\n${declarations.map((line) => `    ${line};`).join("\n")}\n}`;
}

/**
 * Render the face that adjusts a locally installed font to the metrics of the
 * webfont, so the two occupy the same space.
 *
 * @param {Object} face - Face from `buildFallbackFace`.
 * @returns {string} CSS
 */
export function renderFallbackFace(face) {
    const declarations = [
        `font-family: ${quoteFamily(face.family)}`,
        `src: ${face.local.map((name) => `local("${name}")`).join(", ")}`,
        `size-adjust: ${face.sizeAdjust}`,
        `ascent-override: ${face.ascentOverride}`,
        `descent-override: ${face.descentOverride}`,
        `line-gap-override: ${face.lineGapOverride}`,
    ];

    return `@font-face {\n${declarations.map((line) => `    ${line};`).join("\n")}\n}`;
}

/**
 * Group families by the selector their CSS variable belongs in, keeping the
 * order they were configured in.
 *
 * @param {Object[]} families - Resolved families.
 * @param {string} fallbackSelector - Used by a family without its own.
 * @returns {Map<string, Object[]>} families per selector
 */
function groupBySelector(families, fallbackSelector) {
    const groups = new Map();

    for (const family of families) {
        const selector = family.cssSelector || fallbackSelector;
        if (!groups.has(selector)) groups.set(selector, []);
        groups.get(selector).push(family);
    }

    return groups;
}

/**
 * Render the full stylesheet: the @font-face rules followed by a block per
 * selector, exposing every family as a CSS variable.
 *
 * @param {Object[]} families - Resolved families, each with `faces`.
 * @param {Object} [options]
 * @param {string} [options.cssSelector="@theme"] - Selector for families that
 *        do not name one themselves.
 * @returns {string} CSS
 */
export function renderFontsCss(families, { cssSelector = "@theme" } = {}) {
    const fontFaces = families
        .flatMap((family) => [
            ...family.faces.map(renderFontFace),
            ...(family.fallbackFace ? [renderFallbackFace(family.fallbackFace)] : []),
        ])
        .join("\n\n");

    const variables = [...groupBySelector(families, cssSelector)]
        .map(([selector, group]) => {
            const declarations = group
                .map((family) => {
                    const stack = [
                        quoteFamily(family.name),
                        ...(family.fallbackFace
                            ? [quoteFamily(family.fallbackFace.family)]
                            : []),
                        ...family.fallbacks,
                    ];
                    return `    ${family.cssVariable}: ${stack.join(", ")};`;
                })
                .join("\n");
            return `${selector} {\n${declarations}\n}`;
        })
        .join("\n\n");

    const header = `/**
 * This file is automatically generated.
 * Do not edit this file!
 *
 * The font files it references live in "web/fonts/generated"
 * and are generated as well. To change them, update the "fonts"
 * configuration in hyva.config.json and run "npx hyva-fonts".
 */
`;

    if (!families.length) {
        return `${header}\n/* No "fonts" are configured in hyva.config.json. */\n`;
    }

    return `${header}
${fontFaces}

${variables}
`;
}
