/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Layout XML holding the preload hints, written next to the font files it
 * points at, for the user to copy. Preloading cannot be generated into place,
 * since it belongs to the theme's layout rather than to its CSS.
 */
export const PRELOAD_FILE = "hyva-fonts-preload.xml";

/**
 * Path of the layout file the hints belong in, relative to the theme root.
 */
export const LAYOUT_TARGET = "Magento_Theme/layout/default_head_blocks.xml";

/** Comments marking the region of the layout file this command owns. */
export const MARKER_START = "hyva-fonts:start";
export const MARKER_END = "hyva-fonts:end";

/**
 * Escape a value for use in an XML attribute.
 *
 * @param {string} value
 * @returns {string} escaped value
 */
export const escapeXml = (value) =>
    value.replace(/[&<>"']/g, (character) => `&${{ "&": "amp", "<": "lt", ">": "gt", '"': "quot", "'": "apos" }[character]};`);

/**
 * Render the font elements for every family that asked to be preloaded, one
 * comment naming the family followed by its files.
 *
 * @param {Object[]} families - Resolved families, with `files` relative to
 *        the theme's "web/fonts" folder.
 * @returns {string[]} lines, without indentation
 */
export function fontElements(families) {
    return families
        .filter((family) => family.preload && family.faces.length)
        .flatMap((family) => [
            `<!-- ${family.name} -->`,
            ...[...new Set(family.faces.flatMap((face) => face.files))].map(
                (file) => `<font src="fonts/${escapeXml(file)}"/>`
            ),
        ]);
}

/**
 * Render the layout XML preloading the font files of every family that asked
 * for it.
 *
 * Magento's `font` head element renders as a `link` with `rel="preload"`,
 * `as="font"` and `crossorigin="anonymous"`. That last one matters: a font
 * preloaded without it is fetched a second time when the @font-face uses it.
 *
 * @param {Object[]} families - Resolved families, with `files` relative to
 *        the theme's "web/fonts" folder.
 * @returns {string|null} XML, or null when there is nothing to preload
 */
export function renderPreloadXml(families) {
    const lines = fontElements(families);
    if (!lines.length) return null;

    const elements = lines.map((line) => `        ${line}`).join("\n");

    return `<?xml version="1.0"?>
<!--
    This file is automatically generated.
    Do not edit this file!

    Copy everything between the head tags below into your theme's
    ${LAYOUT_TARGET}
    to preload these fonts. Nothing reads this file, it is only here to copy from.

    Keep the two hyva-fonts comments. Once they are in your layout file, this
    command keeps the font elements between them up to date on every run, so
    adding or removing a weight never leaves you preloading a file that is no
    longer there. Everything outside the two comments is left alone.

    Preload only what is needed to render the top of the page. Every preload
    competes with the rest of the page for bandwidth, so preloading a font
    that is used further down makes the page slower rather than faster.
-->
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <!-- ${MARKER_START} -->
${elements}
        <!-- ${MARKER_END} -->
    </head>
</page>
`;
}
